export const motivationQuotes = [
  "İnsanı yaşat ki devlet yaşasın. – Şeyh Edebali",
  "Kaybolmaya başladığınızda yolu öğrenirsiniz.",
  "Adalet mülkün temelidir. – Kanuni Sultan Süleyman",
  "Hedefi olmayan gemiye hiçbir rüzgâr yardım edemez. – Ali Kuşçu",
  "Cihangir olmak istersen kalbine merhamet tohumu ek. – Yavuz Sultan Selim",
  "Bütün savaşlar önce zihinde kazanılır. – Fatih Sultan Mehmet",
  "Savaş sadece kılıçla kazanılmaz, akıl ve strateji de gerekir. – Timur",
  "Hükümdar, halkın refahı için vardır. – I. Bayezid (Yıldırım)",
  "İnsanı yaşat ki devlet yaşasın. – Şeyh Edebali",
  "Disiplin, başarının köprüsüdür. – Jim Rohn",
  "Başarı, tekrar eden küçük alışkanlıkların toplamıdır. – James Clear",
  "Zafere giden yolda, vazgeçmek en büyük yenilgidir. – Vince Lombardi",
  "Çalışkanlık ve azim, başarının en büyük anahtarıdır. – Benjamin Franklin",
  "Geleceğini değiştirmek istiyorsan, bugün yaptıklarını değiştir. – Zig Ziglar",
  "Her gün bir adım at; küçük ilerlemeler büyük sonuçlar getirir. – James Clear",
  "Hedefine ulaşmanın tek yolu, ona doğru adım atmaktır. – Tony Robbins",
  "Başarı, sabır ve azmin birleşimidir. – Brian Tracy",
  "Büyük hayaller kurun ve onlar için çalışın. – Elon Musk",
  "Başarısızlık, sadece yeniden başlama fırsatıdır. – Henry Ford",
  "Sınavın değil, senin azmin önemlidir. – Carol Dweck",
  "Güçlü olmak zorunda değilsin, devam etmek zorundasın. – Ed Latimore",
  "Öğrenmek, zihnin sporudur. – John Dewey",
  "Sınav sadece bir aşamadır, asıl önemli olan gelişimindir. – Angela Duckworth",
  "Çalışmayı bir alışkanlık haline getir, sonra başarının tadını çıkar. – Charles Duhigg",
  "Geleceğin bugünden başlar, nasıl şekilleneceğine sen karar verirsin. – Peter Drucker",
  "İmkansız diye bir şey yoktur, sadece daha çok çalışmak gerekir. – Napoleon Bonaparte",
  "Hedefine ulaşmak istiyorsan, pes etme. – Steve Jobs",
  "Başarı, vazgeçmeyenlerin ödülüdür. – Winston Churchill",
  "Gerçek başarı, düştüğünde kalkmayı bilmektir. – Nelson Mandela",
  "Başarı, planlı çalışmanın sonucudur. – Brian Tracy",
  "Disiplin olmadan yetenek seni bir yere götürmez. – Bill Belichick",
  "Başarıya giden yol, doğru alışkanlıklarla döşenmiştir. – James Clear",
  "Hayallerin için çalış, yoksa başkalarının hayallerine hizmet edersin. – Faruk Eczacıbaşı",
  "Bir hedefin varsa, o hedef için her gün bir şey yap. – Brian Tracy",
  "Sınavdan korkma, onun sana kattıklarını düşün. – Carol Dweck",
  "Hedefsiz bir insan, rotasız bir gemi gibidir. – Seneca",
  "Adalet kutup yıldızı gibidir, yerinde durur ama bütün kainat onun etrafında döner. – Yavuz Sultan Selim",
  "Ekmek aslanın ağzında değil, dişlerinin arasındadır. – Türk Atasözü",
  "Devletin hazinesi ilimdir. – Fatih Sultan Mehmet",
  "Eğitim kökleri acı, meyvesi tatlıdır. – Aristoteles",
  "Gayret kula düşer, tevfik Allah’tandır. – Osman Gazi",
  "Elden gelen öğün olmaz, o da vaktinde bulunmaz. – Türk Atasözü",
  "Bilgi ve akıl, büyük adamları yükselten iki kanattır. – II. Abdülhamid",
  "Azıcık aşım, kaygısız başım. – Türk Atasözü",
  "Her zorluğun arkasında bir kolaylık vardır. – Türk Atasözü",
  "Denize düşen yılana sarılır. – Türk Atasözü",
  "İyi bir başlangıç, yarı yarıya başarıdır. – Aristoteles",
  "Sabır, selamet kapısını açan anahtardır. – Kanuni Sultan Süleyman",
  "Azıcık aş, bol iş huzur getirir. – Türk Atasözü",
  "Ağaç yaşken eğilir. – Türk Atasözü",
  "Göz var, nizam var. – Türk Atasözü",
  "Sakın kader deme, kaderin üstünde bir kader vardır. – Necip Fazıl Kısakürek",
  "Zorluklara sabreden, zaferi hak eder. – Yavuz Sultan Selim",
  "Ümit en büyük servettir. – II. Abdülhamid Han Hazretleri",
  "Ulu çınarlar, fırtınalı iklimlerde yetişir. – Osmanlı Sözü",
  "Akıllı insan, hata yapmaktan korkmaz; çünkü her hata bir derstir. – Mevlana",
  "Başarının sırrı, vazgeçmemekte saklıdır. – Türk Atasözü",
  "Emek olmadan yemek olmaz. – Türk Atasözü",
  "İnsan kendi kendinin mimarıdır. – Fatih Sultan Mehmet",
  "Fazla mal göz çıkarmaz ama çalışmadan gelen mal ömür vermez. – Türk Atasözü",
  "Düşmanını yenmek istersen, ilim ve irfan ile silahlan. – Kanuni Sultan Süleyman",
  "Gideceğin yeri bilmiyorsan, vardığın yerin önemi yoktur. – Türk Atasözü",
  "Küçük adımlar, büyük yolları aşar. – Türk Atasözü",
  "Zamanı geldiğinde meyve veren ağaç, sabrın mükafatını alır. – Osmanlı Sözü",
  "Başarı, sabırla işlenmiş emeğin meyvesidir. – Türk Atasözü",
  "İşleyen demir ışıldar. – Türk Atasözü",
  "Başarı, en çok sabredenlerin hakkıdır. – Mevlana",
  "Zafer, 'devam ediyorum' diyenindir. – Napoleon Bonaparte",
  "Büyük başarılar, küçük adımlarla başlar. – Türk Atasözü",
  "Çalışan kazanır, tembel avunur. – Türk Atasözü",
  "Mutluluk, küçük şeyleri fark etmekten geçer. – Türk Atasözü",
  "Zorluklar, güçlenenlerin basamağıdır. – Osmanlı Sözü",
  "Bir şeyi gerçekten istersen, onun için çalışmalısın. – Elon Musk",
  "Başarısızlık, yeniden başlamanın fırsatıdır. – Henry Ford",
  "Düşmeden nasıl yürüyeceğini öğrenemezsin. – Türk Atasözü",
  "Güçlü olmak, vazgeçmemektir. – Nelson Mandela",
  "Mutluluk, sahip olduklarını sevmektir. – Türk Atasözü",
  "Azim, başarının sırrıdır. – Osmanlı Sözü",
  "Hedefi olmayan bir gemiye hiçbir rüzgar yardım edemez. – Montaigne",
  "Yapabileceğine inan, yarı yolda kalmazsın. – Theodore Roosevelt",
  "Zorluklar olmadan büyümek mümkün değildir. – Türk Atasözü",
  "Hayallerine ulaşmak istiyorsan, yola çıkmalısın. – Tony Robbins",
  "Başarı, ter ve azimle kazanılır. – Thomas Edison",
  "Ne ekersen, onu biçersin. – Türk Atasözü",
  "Hayatın anlamı, her gün bir şeyler öğrenmektir. – Leonardo da Vinci",
  "Gerçek mutluluk, sevdiğin işi yapmaktır. – Steve Jobs",
  "Kaybetmekten korkan, kazanamaz. – Türk Atasözü",
  "Başarı, pes etmeyenlerin ödülüdür. – Winston Churchill",
  "Hata yapmak, öğrenmenin bir parçasıdır. – Albert Einstein",
  "Bir işi başarmak istiyorsan, önce inanmalısın. – Walt Disney",
  "En büyük düşmanın, bahanelerindir. – Türk Atasözü",
  "Mutluluk, hayatın küçük anlarını değerli kılmaktır. – Mevlana",
  "Azimli insan için imkansız yoktur. – Türk Atasözü",
  "Hayat, en çok cesurları ödüllendirir. – Seneca",
  "İmkansız diye bir şey yoktur, sadece denemek gerekir. – Napoleon Bonaparte",
  "Güçlü olmak, pes etmemektir. – Bruce Lee",
  "İyi bir iş, sabır ve emek ister. – Osmanlı Sözü",
  "Büyük işler, büyük hayallerle başlar. – Walt Disney",
  "Hedeflerin yoksa, yollar seni bir yere götürmez. – Türk Atasözü",
  "Gelişmek için değişmek gerekir. – John C. Maxwell",
  "En iyi zaman, şimdi başlamaktır. – Türk Atasözü",
  "Mutlu olmak için büyük şeylere değil, küçük güzelliklere odaklan. – Türk Atasözü",
  "Her yeni gün, yeni bir başlangıçtır. – Türk Atasözü",
  "Yenileceğinden korkan daima yenilir - I. Bayezid",
  "Sultan II. Abdülhamid Han Hz - Cevizin kabuğunu kırıp özüne inmeyen, cevizin hepsini kabuk zanneder.",
  "Fatih Sultan Mehmet Han h.z. - Yapmak istediğimi sakalımın bir teli bile bilseydi, sakalımın o telini hemen koparır ve yakardım.",
  "Yavuz Sultan Selim Han h.z. Devletleri yıkan tüm hatanın altında, nice gururun gafleti yatar.",
  "Kanuni Sultan Süleyman - Ben ölünce bir elimi tabutumun dışına atın. İnsanlar görsünler ki padişah olan Süleyman bu dünyadan eli boş gitmiştir.",
  "Sultan III. Murad Han - Uyan ey gözlerim gafletten uyan Uyan uykusu çok gözlerim uyan Azrail'in kastı canadır inan Uyan ey gözlerim gafletten uyan Uyan uykusu çok gözlerim uyan"
];
